### ISSUE TITLE
redmine 2.6.x and 3.x

### ISSUE THREAD

**Issue by mauro-miatello** [Ultragreen/redmine-appmenuadds#10]
works with them? thanks

**Comment by lecid** [comment]
I'm not sure i haven't made tests for this version

**Comment by mauro-miatello** [comment]
error with 3.3

> Couldn't find all Menutabs with 'id': (all, {:order=>:position}) (found 0 results, but was looking for 2) (ActiveRecord::RecordNotFound)
>   /var/lib/gems/1.9.1/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
>   /var/lib/gems/1.9.1/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:467:in`find_some'
>   /var/lib/gems/1.9.1/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:426:in `find_with_ids'
>   /var/lib/gems/1.9.1/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:71:in`find'
>   /var/lib/gems/1.9.1/gems/activerecord-4.2.6/lib/active_record/querying.rb:3:in `find'
>   /var/lib/gems/1.9.1/gems/activerecord-4.2.6/lib/active_record/core.rb:128:in`find'
>   /mnt/large/var/www/rails/redmine/releases/redmine-3.3.0/plugins/appmenuadds/init.rb:21:in `block in <top (required)>'
>   /mnt/large/var/www/rails/redmine/releases/redmine-3.3.0/lib/redmine/plugin.rb:75:in`instance_eval'
>   /mnt/large/var/www/rails/redmine/releases/redmine-3.3.0/lib/redmine/plugin.rb:75:in `register'
>   /mnt/large/var/www/rails/redmine/releases/redmine-3.3.0/plugins/appmenuadds/init.rb:5:in`<top (required)>'
>   /var/lib/gems/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
>   /var/lib/gems/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
>   /var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
>   /var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in`load_dependency'
>   /var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
>   /mnt/large/var/www/rails/redmine/releases/redmine-3.3.0/lib/redmine/plugin.rb:155:in`block in load'
>   /mnt/large/var/www/rails/redmine/releases/redmine-3.3.0/lib/redmine/plugin.rb:146:in `each'
>   /mnt/large/var/www/rails/redmine/releases/redmine-3.3.0/lib/redmine/plugin.rb:146:in`load'
>   /mnt/large/var/www/rails/redmine/releases/redmine-3.3.0/config/initializers/30-redmine.rb:21:in `<top (required)>'
>   /var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in`load'
>   /var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
>   /var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in`load_dependency'
>   /var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
>   /var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/engine.rb:652:in`block in load_config_initializer'
>   /var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
>   /var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/engine.rb:651:in`load_config_initializer'
>   /var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
>   /var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/engine.rb:615:in`each'
>   /var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
>   /var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/initializable.rb:30:in`instance_exec'
>   /var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
>   /var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/initializable.rb:55:in`block in run_initializers'
>   /usr/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
>   /usr/lib/ruby/1.9.1/tsort.rb:183:in`block (2 levels) in each_strongly_connected_component'
>   /usr/lib/ruby/1.9.1/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
>   /usr/lib/ruby/1.9.1/tsort.rb:219:in`each_strongly_connected_component_from'
>   /usr/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
>   /var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/initializable.rb:44:in`each'
>   /var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
>   /usr/lib/ruby/1.9.1/tsort.rb:203:in`each_strongly_connected_component_from'
>   /usr/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
>   /usr/lib/ruby/1.9.1/tsort.rb:180:in`each'
>   /usr/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
>   /usr/lib/ruby/1.9.1/tsort.rb:148:in`tsort_each'
>   /var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
>   /var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/application.rb:352:in`initialize!'
>   /mnt/large/var/www/rails/redmine/releases/redmine-3.3.0/config/environment.rb:14:in `<top (required)>'
>   config.ru:3:in`require'
>   config.ru:3:in `block in <main>'
>   /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in`instance_eval'
>   /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
>   config.ru:1:in`new'
>   config.ru:1:in `<main>'
>   /var/lib/gems/1.9.1/gems/passenger-4.0.45/helper-scripts/rack-preloader.rb:112:in`eval'
>   /var/lib/gems/1.9.1/gems/passenger-4.0.45/helper-scripts/rack-preloader.rb:112:in `preload_app'
>   /var/lib/gems/1.9.1/gems/passenger-4.0.45/helper-scripts/rack-preloader.rb:158:in`module:App'
>   /var/lib/gems/1.9.1/gems/passenger-4.0.45/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
>   /var/lib/gems/1.9.1/gems/passenger-4.0.45/helper-scripts/rack-preloader.rb:28:in`<main>'
